## Learning Pandas by a kaggle dataset and course

Core concepts:
1. Creating, reading and writing dataframes and series
2. Indexing and selecting
3. Functions and maps
4. Grouping and sorting
5. Data types and handling missing values
6. Renaming and combining features

Dataset used: [Wine Reviews by Kaggle user 'zackthoutt']([https://www.kaggle.com/zynicide/wine-reviews)

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 5)

## Creating, Reading, Writing dataframes & series

### Dataframes
A dataframe is a table, that can be initialized, e.g. using a dictionary object.

In [2]:
# Row labels: Ascending counts
pd.DataFrame({'Yes': [1, 42], 'No':['test', 46]})

   Yes    No
0    1  test
1   42    46

In [3]:
# Row labels: Indices passed to the dataframe
pd.DataFrame({'Yes': [1, 42], 'No':[3, 46]}, index=['Person A', 'Person B'])

          Yes  No
Person A    1   3
Person B   42  46

### Series
Series are sequences of data values, that can be initialized, e.g. using a list.

In [4]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
# Assign an index parameter to the rows.
# Note that a Series doesn't have a column name.
pd.Series([1,2,3,4,5], index=[2016, 2017, 2018, 2019, 2020], name='Product A')

2016    1
2017    2
2018    3
2019    4
2020    5
Name: Product A, dtype: int64

Dataframes can be seen as multiple Series 'glued' or 'stacked' together.

### Reading files

In [6]:
# Creating a table from a comma-separated-values (csv) file
wine_reviews = pd.read_csv('./data/winemag-data-130k-v2.csv', index_col=0)
wine_reviews.shape

(129971, 13)

Without the index_col parameter, Pandas would not pick up the first column (that corresponds to the row number) automatically. Note that the `read_csv` function can be specified with over 30 optional parameters.

In [7]:
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

## Indexing, Selecting, Assigning

In [8]:
wine_reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [9]:
# Attributes of a Python object can be accessed by calling
# it on the object, e.g. 'book.title'.
# Columns in a dataframe can be accessed similarly.
wine_reviews.country

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [10]:
# Python dictionary values can be accessed using the indexing
# operator []. The same can be done with columns in a dataframe.
wine_reviews['country']

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

The indexing operator `[]` has the advantage that all column names can be handled, e.g. `reviews.country providence` would not work but `reviews['country providence']` would.

### Index-based selecting

Index based selecting is done with the `iloc` functionality. Here, data is selected based on its numerical position.

In [11]:
# E.g. getting first three entries of second column.
wine_reviews.iloc[:3, 1]

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
Name: description, dtype: object

In [12]:
# Passing a list to select entries in first column.
wine_reviews.iloc[[0,2,4], 1]

0    Aromas include tropical fruit, broom, brimston...
2    Tart and snappy, the flavors of lime flesh and...
4    Much like the regular bottling from 2012, this...
Name: description, dtype: object

In [13]:
# Last five elements of a column
wine_reviews.iloc[-5:, 0]

129966    Germany
129967         US
129968     France
129969     France
129970     France
Name: country, dtype: object

### Label-based selecting

Label based selection is done using the `loc` operator. Here the index value, and not the position, matters to locate entries.

In [14]:
wine_reviews.loc[0:3, 'country']

0       Italy
1    Portugal
2          US
3          US
Name: country, dtype: object

`iloc` treats the dataframe like a matrix and ignores the dataset's indices. One operation that is much easier using label-based selection:

In [15]:
wine_reviews.loc[:, ['taster_name', 'points']]

          taster_name  points
0       Kerin O’Keefe      87
1          Roger Voss      87
...               ...     ...
129969     Roger Voss      90
129970     Roger Voss      90

[129971 rows x 2 columns]

Attention! `iloc` and `loc` use different indexing schemes: While `iloc` follows the Python stdlib indexing scheme, meaning that `0:10` selects entries `0,...,9`, `loc` includes the last entry, meaning that `0:10` selects entries `0,...,10`. 

Consider e.g. an alphabetic order of animals with index values `Alpaca,...,Zebra`, then `df.loc['Alpaca':'Zebra']` can be a convenient usage.

Otherwise, `loc` and `iloc`'s usage are similar.

### Changing the index
The index is mutable, using `set_index()`. E.g. change the index to the title field. This can be useful if there is a better choice for the index available.

In [16]:
wine_reviews.set_index('title')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace),France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

### Conditional selecting
Interesting things about the data require us to ask questions, based on a condition. A created boolean can then be used inside of `loc`. E.g. if we are interested in wine from a specific country.

In [17]:
wine_reviews.loc[wine_reviews.country == 'Italy']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

If we further want to check wines from Italy, that have a rating higher than 90:

In [18]:
wine_reviews.loc[
    (wine_reviews.country == 'Italy') & 
    (wine_reviews.points >= 90)
]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

Wine that is from Italy OR has a rating higher than 90:

In [19]:
wine_reviews.loc[
    (wine_reviews.country == 'Italy') |
    (wine_reviews.points >= 90)
]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

Pandas has a few built in conditional selectors, e.g. `isin` and `isnull`. `isin` is can be used to select data whose value is in a list of values, e.g.

In [20]:
wine_reviews.loc[wine_reviews.country.isin(['Italy', 'France'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

`isnull` and `notnull` can be used to highlight values that are (not) empty (`NaN`). Lacking price tags in the data set:

In [21]:
wine_reviews.loc[wine_reviews.price.notnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

### Assigning data to a dataframe

In [22]:
# Constant values
wine_reviews['critic'] = 'no one'

# Via iterable
wine_reviews['index_backwards'] = range(len(wine_reviews), 0, -1)

## Summary functions and maps
There is usually always a helpful pandas function to summarize the statistics about a column in a dataframe or series.

In [23]:
print(wine_reviews.price.describe(), "\n")
print(wine_reviews.country.describe(), "\n")
print(wine_reviews.points.mean(), "\n")
print(wine_reviews.country.unique(), "\n")
print(wine_reviews.country.value_counts(), "\n")

count    120975.000000
mean         35.363389
             ...
75%          42.000000
max        3300.000000
Name: price, Length: 8, dtype: float64

count     129908
unique        43
top           US
freq       54504
Name: country, dtype: object

88.44713820775404

['Italy' 'Portugal' 'US' 'Spain' 'France' 'Germany' 'Argentina' 'Chile'
 'Australia' 'Austria' 'South Africa' 'New Zealand' 'Israel' 'Hungary'
 'Greece' 'Romania' 'Mexico' 'Canada' nan 'Turkey' 'Czech Republic'
 'Slovenia' 'Luxembourg' 'Croatia' 'Georgia' 'Uruguay' 'England' 'Lebanon'
 'Serbia' 'Brazil' 'Moldova' 'Morocco' 'Peru' 'India' 'Bulgaria' 'Cyprus'
 'Armenia' 'Switzerland' 'Bosnia and Herzegovina' 'Ukraine' 'Slovakia'
 'Macedonia' 'China' 'Egypt']

US        54504
France    22093
          ...
China         1
Egypt         1
Name: country, Length: 43, dtype: int64

### Maps
Maps can be used to transform one set of values and map them to another set of values (e.g. when we want to create new representations). 

The function passed to `map()` should expect a single value (from the series) and also return a single value (returning a new series).

`apply()`is the equivalent, if we want to transform the whole dataframe.

In [24]:
review_points_mean = wine_reviews.points.mean()
wine_reviews.points.map(
    lambda p: p - review_points_mean)

0        -1.447138
1        -1.447138
            ...
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [25]:
def shift_by_mean(row):
    row.points = row.points - review_points_mean
    return row
wine_reviews.apply(shift_by_mean, axis='columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,no one,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,no one,129970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,no one,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,no one,1

When we use `wine_reviews.apply()` with `axis='index'`, instead of passing a function that transforms each row, we need to give a function that transforms each column. 

Note that `map()` and `apply()` return new series and dataframes, but don't modify the original data:

In [26]:
wine_reviews.loc[0, 'points']

87

In [27]:
# Fast shifting by mean
review_points_mean = wine_reviews.points.mean()
wine_reviews.points - review_points_mean

0        -1.447138
1        -1.447138
            ...
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

Pandas looks at this expression and understands that the mean (single value) has to be substracted from the points column (series, not single value!). 

This also works if the series are of equal length. For example, we can combine the country and region information by doing

In [28]:
wine_reviews.country + ' - ' + wine_reviews.region_1

0            Italy - Etna
1                     NaN
               ...
129969    France - Alsace
129970    France - Alsace
Length: 129971, dtype: object

This operation is also faster than `map()` or `apply()`, since this uses builtins of pandas. All Python standard operators (like `+`, `==` etc.) work that way.

## Grouping and sorting
`groupby()` creates a group (slice of dataframe) containing only data that matches a value. This slice can then be manipulated, using the `apply()` method.

In [45]:
# Replication of the value_counts() function
print(wine_reviews.groupby('points').points.count(), "\n")

# Checking the minimum price of each point category
print(wine_reviews.groupby('points').price.min(), "\n")

# Get the title from the first wine reviewed from each winery
print(wine_reviews.groupby('winery').apply(
    lambda df: df.title.iloc[0]))

points
80     397
81     692
      ...
99      33
100     19
Name: points, Length: 21, dtype: int64

points
80      5.0
81      5.0
       ...
99     44.0
100    80.0
Name: price, Length: 21, dtype: float64

winery
1+1=3                          1+1=3 NV Rosé Sparkling (Cava)
10 Knots                 10 Knots 2010 Viognier (Paso Robles)
                                  ...
àMaurice    àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                         Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

It is also possible to group by more than one column. For example, grouping by country and province and then get the best wine by country and province:

In [48]:
wine_reviews.groupby(['country', 'province']).apply(
    lambda df: df.loc[df.points.idxmax()]
)

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
...                               ...
Uruguay   San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
...                                                                       ...
Uruguay   San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                          designation  points  price  \
country   province
Argentina Mendoza Province           Nicasia Vineyard      97  120.0
          Other                               Reserva      95   90.0
...                                               ...     ...    ...
Uruguay   San Jose           El Preciado Gran Reserva      87   50.0
          Uruguay           Blend 002 Limited Edition      91   22.0

                                    province region_1 region_2  \
country   province
Argentina Mendoza Province  Mendoza Province  Mendoza      NaN
          Other                        Other    Salta      NaN
...                                      ...      ...      ...
Uruguay   San Jose                  San Jose      NaN      NaN
          Uruguay                    Uruguay      NaN      NaN

                                  taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province  Michael Schachner           @wineschach
          Other             Michael Schachner           @wineschach
...                                       ...                   ...
Uruguay   San Jose          Michael Schachner           @wineschach
          Uruguay           Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
...                                                                       ...
Uruguay   San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery  \
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
...                                           ...                   ...
Uruguay   San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

                            critic  index_backwards
country   province
Argentina Mendoza Province  no one            47217
          Other             no one            51668
...                            ...              ...
Uruguay   San Jose          no one            90073
          Uruguay           no one            90610

[425 rows x 15 columns]

`agg` is a method that can run multiple different functions on a dataframe simultaneously:

In [57]:
def get_mean(col):
    return col.mean()
wine_reviews.groupby(['country']).price.agg([len, min, max, get_mean])

            len   min    max   get_mean
country
Argentina  3800   4.0  230.0  24.510117
Armenia       2  14.0   15.0  14.500000
...         ...   ...    ...        ...
Ukraine      14   6.0   13.0   9.214286
Uruguay     109  10.0  130.0  26.403670

[43 rows x 4 columns]

## Multi-indexes
`groupby()` differs from dataframe and series objects since it can sometimes result in creating a multi-index (remember: dataframe and series have a single-label index). A multi-index has multiple levels:

In [60]:
provinces = wine_reviews.groupby(['country', 'province']).description.agg([len])
print(provinces)
print(provinces.index)
print(type(provinces.index))

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]
MultiIndex([('Argentina',  'Mendoza Province'),
            ('Argentina',             'Other'),
            (  'Armenia',           'Armenia'),
            ('Australia',   'Australia Other'),
            ('Australia',   'New South Wales'),
            ('Australia',   'South Australia'),
            ('Australia',          'Tasmania'),
            ('Australia',          'Victoria'),
            ('Australia', 'Western Australia'),
            (  'Austria',           'Austria'),
            ...
            (       'US',        'Washington'),
            (       'US', 'Washington-Oregon'),
            (  'Ukraine',           'Ukraine'),
            (  'Uruguay',         'Atlantida'),
            (  'Uruguay',         'Canelones'),
            (  'Uruguay',           'Juanico'),
            (  'Uruguay',        'Montevideo'),
            (  'Uruguay',          'Progreso'),
            (  'Uruguay',          'San Jose'),
            (  'Uruguay',           'Uruguay')],
           names=['country', 'province'], length=425)
<class 'pandas.core.indexes.multi.MultiIndex'>

In [61]:
provinces

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]

The `reset_index()` method can be used to converting back to a regular index:

In [62]:
provinces.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
..         ...               ...   ...
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

### Sorting
Grouping returns the data in the index order. Ordering by value becomes possible by `sort_values()`:

In [70]:
# Sort values by column 'len'
print(provinces.sort_values(by='len', ascending=False), "\n\n")

# Sort by index values
print(provinces.sort_index(), "\n\n")

# Sort by more than one column
print(provinces.sort_values(by=['country', 'len']))

                      len
country province
US      California  36247
        Washington   8639
...                   ...
Chile   Coelemu         1
Greece  Beotia          1

[425 rows x 1 columns]


                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]


                             len
country   province
Argentina Other              536
          Mendoza Province  3264
...                          ...
Uruguay   Uruguay             24
          Canelones           43

[425 rows x 1 columns]